export const images = {
  intro: require('../Assets/birthday.png'),
  top: require('../Assets/top.png'),
  line: require('../Assets/line.png'),
  bottom: require('../Assets/bottom.png'),
  intro2: require('../Assets/birthday2.png'),
  birthdayBg: require('../Assets/birthdayBG.png'),
  birthdayHeader: require('../Assets/Birthdayhearders.png'),
  birthdayBGH: require('../Assets/birthdayBGH.png'),
  birthdayBG: require('../Assets/birthdayBG.png'),
  google: require('../Assets/google.png'),
  facebook: require('../Assets/facebook.png'),
  linkedin: require('../Assets/linkedin.png'),
  party: require('../Assets/party.png'),
  hideEye: require('../Assets/hideEye.png'),
  showEye: require('../Assets/showEye.png'),
  winIcon: require('../Assets/winIcon.png'),
  winPerson: require('../Assets/winPerson.png'),
  profile: require('../Assets/profile.png'),
  star: require('../Assets/star.png'),
  heart: require('../Assets/heart.png'),
  clock: require('../Assets/clock.png'),
  trophy: require('../Assets/trophy.png'),
  familyIcon: require('../Assets/familyQuizdp.png'),
  streak: require('../Assets/streak.png'),
  avatar: require('../Assets/avatar.png'),
  cake: require('../Assets/cake.png'),
  partymin: require('../Assets/partymin.png'),
  avatar: require('../Assets/avatar.png'),
  editProfileIcon: require('../Assets/editProfileIcon.png'),
  add: require('../Assets/add.png'),
  back: require('../Assets/back.png'),
  more: require('../Assets/more.png'),
  home: require('../Assets/home.png'),
  notifications: require('../Assets/notifications.png'),
  user: require('../Assets/user.png'),
  pencil: require('../Assets/pencil.png'),
  share: require('../Assets/share.png'),
};

export const colors = {
  primary: '#715CE4',
  secondary: '#98FF98',
};
